#Get all products
# GET http://localhost:5000/api/v1/products

# Add a product 

POST http://localhost:5000/api/v1/products
content-type: application/json

{
    "prid":1,
    "name":"iphone 15",
    "price":71000,
    "image":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/k/l/l/-original-imagtc5fz9spysyk.jpeg?q=70&crop=false"
}